// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlNIMJV_lyIYYGpL7I9pbdOYnFoDc74k',
    appId: '1:963239790335:web:88dc030fb6c7e177dcaeca',
    messagingSenderId: '963239790335',
    projectId: 'splitmate-6b600',
    authDomain: 'splitmate-6b600.firebaseapp.com',
    storageBucket: 'splitmate-6b600.firebasestorage.app',
    measurementId: 'G-FW9PW2H4N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9WkMcBSkzSbAVCoiMbp0WoExvMy12ZM',
    appId: '1:963239790335:android:3c02e893331e3e79dcaeca',
    messagingSenderId: '963239790335',
    projectId: 'splitmate-6b600',
    storageBucket: 'splitmate-6b600.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPrxPTVMrrRO_jHVb6cXxEuTdfLDQLX-s',
    appId: '1:963239790335:ios:95732b152e3c6ae7dcaeca',
    messagingSenderId: '963239790335',
    projectId: 'splitmate-6b600',
    storageBucket: 'splitmate-6b600.firebasestorage.app',
    iosClientId: '963239790335-h2drlsfn07p2mp4vh5jthhv4974voeck.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPrxPTVMrrRO_jHVb6cXxEuTdfLDQLX-s',
    appId: '1:963239790335:ios:95732b152e3c6ae7dcaeca',
    messagingSenderId: '963239790335',
    projectId: 'splitmate-6b600',
    storageBucket: 'splitmate-6b600.firebasestorage.app',
    iosClientId: '963239790335-h2drlsfn07p2mp4vh5jthhv4974voeck.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitMate',
  );
}
